# Generated by Django 2.1.15 on 2022-09-25 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_to_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('slug', models.SlugField(max_length=500, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, default='')),
                ('reply', models.TextField(blank=True, default='')),
                ('cus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
                ('ord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_product.Add_to_cart')),
            ],
        ),
        migrations.CreateModel(
            name='Manage_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=1000)),
                ('image', models.ImageField(upload_to='product_image')),
                ('price', models.IntegerField(blank=True, default=0)),
                ('availability', models.BooleanField(default=True, null=True)),
                ('slug', models.SlugField(max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='add_to_cart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_product.Manage_product'),
        ),
    ]
