# Generated by Django 2.1.15 on 2022-10-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='if_seen',
            field=models.IntegerField(null=True),
        ),
    ]
