# Generated by Django 4.0.4 on 2022-08-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_product',
            name='price',
            field=models.IntegerField(max_length=1000),
        ),
    ]
