# Generated by Django 4.0.4 on 2022-08-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0002_alter_manage_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='manage_product',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='product_image/'),
        ),
        migrations.AlterField(
            model_name='manage_product',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manage_product',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
