# Generated by Django 2.1.15 on 2022-10-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0003_auto_20221002_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_cart',
            name='dine_in',
        ),
        migrations.RemoveField(
            model_name='add_to_cart',
            name='take_out',
        ),
        migrations.AddField(
            model_name='add_to_cart',
            name='to_di',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
