# Generated by Django 2.1.15 on 2022-10-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0004_auto_20221002_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='to_di',
            field=models.CharField(max_length=10),
        ),
    ]
