# Generated by Django 2.1.15 on 2022-10-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0005_auto_20221002_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_product',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='manage_product',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='manage_product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
