# Generated by Django 4.0.4 on 2022-08-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0006_alter_manage_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_product',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
