# Generated by Django 2.1.15 on 2022-10-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0006_auto_20221002_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
