# Generated by Django 4.0.4 on 2022-08-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0008_add_to_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_cart',
            name='customer',
        ),
    ]
