# Generated by Django 2.1.15 on 2022-10-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0008_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='new',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
