# Generated by Django 2.1.15 on 2022-10-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0009_auto_20221009_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
