# Generated by Django 2.1.15 on 2022-10-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0010_inventory_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_product',
            name='new',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manage_product',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manage_product',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manage_product',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
