# Generated by Django 2.1.15 on 2022-10-23 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0011_auto_20221016_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
