# Generated by Django 4.0.4 on 2022-08-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0011_alter_add_to_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
