# Generated by Django 4.0.4 on 2022-08-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0012_add_to_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='slug',
            field=models.SlugField(max_length=500, null=True),
        ),
    ]
