# Generated by Django 2.1.15 on 2022-10-23 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0012_auto_20221023_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
