# Generated by Django 4.0.4 on 2022-08-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0013_add_to_cart_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_product',
            name='availability',
            field=models.CharField(default='available', max_length=10, null=True),
        ),
    ]
