# Generated by Django 4.0.4 on 2022-08-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0014_manage_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_product',
            name='availability',
            field=models.CharField(default='available', max_length=50, null=True),
        ),
    ]
