# Generated by Django 2.1.15 on 2022-10-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0016_auto_20221023_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='Date_inv',
        ),
    ]
