# Generated by Django 4.0.4 on 2022-08-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0017_remove_add_to_cart_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_product',
            name='availability',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
