# Generated by Django 4.0.4 on 2022-08-29 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0021_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reply',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
