# Generated by Django 4.0.4 on 2022-08-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0022_alter_feedback_feedback_alter_feedback_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reply',
            field=models.TextField(null=True),
        ),
    ]
