# Generated by Django 4.0.4 on 2022-08-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0023_alter_feedback_feedback_alter_feedback_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reply',
            field=models.TextField(blank=True, default=''),
        ),
    ]
