# Generated by Django 4.0.4 on 2022-08-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0024_alter_feedback_feedback_alter_feedback_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='pro',
        ),
        migrations.AddField(
            model_name='feedback',
            name='ord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_product.add_to_cart'),
        ),
    ]
