# Generated by Django 4.0.4 on 2022-08-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
