# Generated by Django 4.0.4 on 2022-08-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0009_remove_add_to_cart_customer'),
        ('main', '0004_alter_customer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
